version: '3.1'
services:
  app:
    container_name: order-processing-service
    image: order-processing-service
    build: ./
    ports:
      - '9090:8080'
    expose:
      - '8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/orders
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders
